/**
 * Compatibility milestone only: real pinned SDK root + package-built Flue facet.
 * This is NOT a production Activity replacement. No host adapter is implemented
 * here in RED: dynamic resolution, scheduler delegation and restricted operation
 * admission remain the missing behavior. The upstream transport intentionally
 * accepts effects so blanket denial and absent authority checks cannot pass.
 */
import { WorkerEntrypoint } from 'cloudflare:workers';
import { Agent, getAgentByName } from 'agents';
import type { FixtureActivity } from './loader-worker';

export type NativeArtifact = {
  schemaVersion: 1; sourceCommit: string;
  versions: { runtime: string; vitePlugin: string; agents: string };
  className: 'FlueDispatcherAgent'; compatibilityDate: string; compatibilityFlags: string[];
  mainModule: string; modules: Record<string, { js: string }>;
};
export type NativeDelivery = {
  activityId: string; generation: number; operationId: string; requestDigest: string;
  marker: string; mode: 'read' | 'hold' | 'receipt-window' | 'unknown' | 'probe';
};
export type FlueFixtureCommand =
  | { action: 'configure'; artifact: NativeArtifact; digest: string }
  | { action: 'send'; delivery: NativeDelivery }
  | { action: 'snapshot' }
  | { action: 'release' }
  | { action: 'evict' }
  | { action: 'abort' };

type Facet = Fetcher & {
  _cf_initAsFacet(name: string, parentPath: Array<{ className: string; name: string }>, identityName: string): Promise<void>;
  fixtureSnapshot(): Promise<unknown>;
};
type NativeEnv = {
  FLUE_ROOT: DurableObjectNamespace<FixtureFlueRoot>;
  ACTIVITY: DurableObjectNamespace<FixtureActivity>;
  LOADER: { get(id: string, code: () => Promise<unknown>): { getDurableObjectClass(name: string): unknown } };
};
export type ExternalReceipt = NativeDelivery & { sequence: number; path: string };

/** Real SDK owns all physical alarms/fiber machinery. No copied scheduler. */
export class FixtureFlueRoot extends Agent<NativeEnv> {
  private readonly instance = crypto.randomUUID();
  private facet?: Promise<Facet>;
  private releaseBarrier?: () => void;

  override async alarm() {
    await this.ctx.storage.put('fixture:alarm-deliveries', (await this.ctx.storage.get<number>('fixture:alarm-deliveries') ?? 0) + 1);
    return super.alarm();
  }

  async configure(artifact: NativeArtifact, digest: string) {
    const bytes = new TextEncoder().encode(JSON.stringify(artifact));
    const actual = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), b => b.toString(16).padStart(2, '0')).join('');
    if (actual !== digest || bytes.length > 8 * 1024 * 1024 || Object.keys(artifact.modules).length > 128 ||
      artifact.className !== 'FlueDispatcherAgent' || artifact.versions.runtime !== '2.1.0' || artifact.versions.agents !== '0.20.1') {
      return { ok: false, reason: 'fixture-artifact-rejected' };
    }
    // Keep large generated bytes out of a single DO KV value. Eviction must
    // reload these exact bytes, never a moving file path or package reference.
    const chunkSize = 48 * 1024;
    for (let i = 0; i < bytes.length; i += chunkSize) await this.ctx.storage.put(`fixture:artifact:${i / chunkSize}`, bytes.slice(i, i + chunkSize));
    await this.ctx.storage.put({ 'fixture:artifact-chunks': Math.ceil(bytes.length / chunkSize), 'fixture:digest': digest });
    this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS fixture_parent_secret (secret TEXT)');
    this.ctx.storage.sql.exec("INSERT INTO fixture_parent_secret VALUES ('parent-only-sentinel')");
    return { ok: true, digest, sourceCommit: artifact.sourceCommit };
  }

  private async artifact(): Promise<NativeArtifact> {
    const count = await this.ctx.storage.get<number>('fixture:artifact-chunks');
    if (!count) throw new Error('Pinned native artifact not configured');
    const decoder = new TextDecoder();
    let json = '';
    for (let i = 0; i < count; i++) json += decoder.decode(await this.ctx.storage.get<Uint8Array>(`fixture:artifact:${i}`), { stream: true });
    return JSON.parse(json + decoder.decode());
  }

  private child(): Promise<Facet> {
    return this.facet ??= (async () => {
      const artifact = await this.artifact();
      const digest = await this.ctx.storage.get<string>('fixture:digest');
      const { exports } = this.ctx as unknown as { exports: {
        FixtureFlueTransport(options: { props: { activityId: string } }): Fetcher;
      } };
      const worker = this.env.LOADER.get(`fixture:${this.name}:${digest}`, async () => ({
        compatibilityDate: artifact.compatibilityDate, compatibilityFlags: artifact.compatibilityFlags,
        mainModule: artifact.mainModule, modules: artifact.modules,
        env: { OPERATOR: exports.FixtureFlueTransport({ props: { activityId: this.name } }) },
        globalOutbound: null,
      }));
      const { facets } = this.ctx as unknown as { facets: { get(name: string, init: () => unknown): Facet } };
      const child = facets.get('dispatcher', () => ({
        class: worker.getDurableObjectClass(artifact.className), id: this.env.FLUE_ROOT.idFromName('dispatcher'),
      }));
      // Pinned SDK bootstrap, not an imitation. RED intentionally exposes the
      // unsupported static root lookup in the generated dynamic Worker. GREEN
      // needs the narrow bridge/resolver before any production base-class change.
      await child._cf_initAsFacet('dispatcher', [{ className: 'FixtureFlueRoot', name: this.name }], 'dispatcher');
      return child;
    })();
  }

  async send(delivery: NativeDelivery) {
    try {
      const response = await (await this.child()).fetch(new Request('https://flue.internal/dispatcher', {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ kind: 'user', body: JSON.stringify(delivery) }),
      }));
      return { status: response.status, body: await response.json() };
    } catch (error) {
      return { status: 501, body: { stage: 'native-facet-admission', error: String(error) } };
    }
  }

  async snapshot() {
    let conversation: unknown = null;
    let facet: unknown = null;
    let failure: string | undefined;
    try {
      const child = await this.child();
      const response = await child.fetch(new Request('https://flue.internal/dispatcher'));
      conversation = await response.json();
      facet = await child.fixtureSnapshot();
    } catch (error) { failure = String(error); }
    return {
      instance: this.instance, conversation, facet, failure,
      alarmDeliveries: await this.ctx.storage.get<number>('fixture:alarm-deliveries') ?? 0,
      barrierReached: await this.ctx.storage.get<boolean>('fixture:barrier-reached') ?? false,
      external: await this.ctx.storage.get<ExternalReceipt[]>('fixture:external') ?? [],
      activity: await this.env.ACTIVITY.getByName(this.name).getBrowserDetail(),
      digest: await this.ctx.storage.get('fixture:digest'),
    };
  }

  async release() {
    await this.ctx.storage.put('fixture:released', true);
    this.releaseBarrier?.();
    return { released: true };
  }
  evict() { this.ctx.abort('Native Flue fixture root and facet eviction'); }
  async abort() {
    const response = await (await this.child()).fetch(new Request('https://flue.internal/dispatcher/abort', { method: 'POST' }));
    return { status: response.status, body: await response.json() };
  }

  /** Synthetic upstream, deliberately NOT the missing parent authority bridge. */
  async transport(request: Request): Promise<Response> {
    const path = new URL(request.url).pathname;
    if (path === '/fixture/inference') {
      // Official Workers-AI adapter consumes OpenAI-compatible SSE. Exactly one
      // real Flue tool is offered by the deterministic model, no model billing.
      const body = await request.json() as { input: { messages?: Array<{ role: string }> } };
      const done = body.input.messages?.at(-1)?.role === 'tool';
      const chunks = done ? [{ choices: [{ index: 0, delta: { content: 'Assessment complete' }, finish_reason: 'stop' }] }] : [
        { choices: [{ index: 0, delta: { tool_calls: [{ index: 0, id: 'fixture-tool', type: 'function',
          function: { name: 'assess_renovate', arguments: '{}' } }] }, finish_reason: null }] },
        { choices: [{ index: 0, delta: {}, finish_reason: 'tool_calls' }] },
      ];
      return new Response(chunks.map(chunk => `data: ${JSON.stringify(chunk)}\n\n`).join('') + 'data: [DONE]\n\n', {
        headers: { 'content-type': 'text/event-stream' },
      });
    }
    const delivery = await request.json() as NativeDelivery;
    if (path === '/fixture/barrier') {
      await this.ctx.storage.put('fixture:barrier-reached', true);
      if (!await this.ctx.storage.get('fixture:released')) await new Promise<void>(resolve => { this.releaseBarrier = resolve; });
      return Response.json({ released: true });
    }
    const external = await this.ctx.storage.get<ExternalReceipt[]>('fixture:external') ?? [];
    const receipt = { ...delivery, path, sequence: external.length + 1 };
    external.push(receipt);
    await this.ctx.storage.put('fixture:external', external);
    if (delivery.mode === 'unknown') {
      await this.ctx.storage.put('fixture:barrier-reached', true);
      // Accepted externally, response deliberately lost. Recovery must not
      // replay this ledger entry just because ToolStep did not record it.
      await new Promise<void>(resolve => { this.releaseBarrier = resolve; });
      throw new Error('Fixture lost external response');
    }
    return Response.json({ accepted: true, receipt, evidence: { repositoryId: 123, botId: 29139614, head: 'a'.repeat(40), checks: ['success'] } });
  }
}

export class FixtureFlueTransport extends WorkerEntrypoint<NativeEnv> {
  async fetch(request: Request) {
    const { activityId } = this.ctx.props as { activityId: string };
    return (await getAgentByName(this.env.FLUE_ROOT, activityId)).transport(request);
  }
}

export async function flueFixture(request: Request, env: NativeEnv) {
  const id = new URL(request.url).searchParams.get('activity')!;
  const root = await getAgentByName(env.FLUE_ROOT, id);
  const command = await request.json<FlueFixtureCommand>();
  switch (command.action) {
    case 'configure': return Response.json(await root.configure(command.artifact, command.digest));
    case 'send': return Response.json(await root.send(command.delivery));
    case 'snapshot': return Response.json(await root.snapshot());
    case 'release': return Response.json(await root.release());
    case 'abort': return Response.json(await root.abort());
    case 'evict':
      await root.evict().catch(() => {});
      return Response.json({ evicted: true });
  }
}
