/**
 * Compatibility milestone only: real pinned SDK root + package-built Flue facet.
 * This is NOT a production Activity replacement. No host adapter is implemented
 * here in RED: dynamic resolution, scheduler delegation and restricted operation
 * admission remain the missing behavior. The upstream transport intentionally
 * accepts effects so blanket denial and absent authority checks cannot pass.
 */
import { WorkerEntrypoint } from 'cloudflare:workers';
import { Agent, getAgentByName, type RetryOptions, type Schedule, type ScheduleCriteria } from 'agents';
import type { FixtureActivity } from './loader-worker';

export type NativeArtifact = {
  schemaVersion: 1; sourceCommit: string;
  versions: { runtime: string; vitePlugin: string; agents: string };
  className: 'FlueDispatcherAgent'; compatibilityDate: string; compatibilityFlags: string[];
  mainModule: string; modules: Record<string, { js: string }>;
};
export type NativeDelivery = {
  activityId: string; generation: number; operationId: string; requestDigest: string;
  marker: string; mode: 'read' | 'hold' | 'receipt-window' | 'unknown' | 'probe';
};
export type FlueFixtureCommand =
  | { action: 'configure'; artifact: NativeArtifact; digest: string }
  | { action: 'send'; delivery: NativeDelivery }
  | { action: 'snapshot' }
  | { action: 'release' }
  | { action: 'evict' }
  | { action: 'abort' };

type FacetPath = readonly Readonly<{ className: string; name: string }>[];
type Facet = Fetcher & {
  _cf_initAsFacet(name: string, parentPath: Array<{ className: string; name: string }>, identityName: string): Promise<void>;
  _cf_checkRunFibersForFacet(ownerPath: FacetPath): Promise<number>;
  _cf_dispatchScheduledCallback(ownerPath: FacetPath, row: unknown): Promise<boolean>;
  fixtureSnapshot(): Promise<unknown>;
};
type NativeEnv = Cloudflare.Env & {
  FLUE_ROOT: DurableObjectNamespace<FixtureFlueRoot>;
  ACTIVITY: DurableObjectNamespace<FixtureActivity>;
  LOADER: { get(id: string, code: () => Promise<unknown>): { getDurableObjectClass(name: string): unknown } };
};
type AgentsFacetRootBridge = Pick<Agent<NativeEnv>,
  '_cf_scheduleForFacet' | '_cf_scheduleEveryForFacet' | '_cf_getScheduleForFacet'
  | '_cf_listSchedulesForFacet' | '_cf_cancelScheduleForFacet' | '_cf_acquireFacetKeepAlive'
  | '_cf_releaseFacetKeepAlive' | '_cf_registerFacetRun' | '_cf_unregisterFacetRun'>;
type FacetBridgeBinding = { generation: number; status: 'current' | 'stale' | 'denied' };
type FixtureFlueRootStub = DurableObjectStub<FixtureFlueRoot>;
export type ExternalReceipt = NativeDelivery & { sequence: number; path: string };

/** Real SDK owns all physical alarms/fiber machinery. No copied scheduler. */
export class FixtureFlueRoot extends Agent<NativeEnv> {
  private readonly instance = crypto.randomUUID();
  private facet?: Promise<Facet>;
  private releaseBarrier?: () => void;
  private reboundGeneration?: number;

  constructor(ctx: DurableObjectState, env: NativeEnv) {
    super(ctx, env);
    ctx.blockConcurrencyWhile(async () => {
      const active = await ctx.storage.get<{ submissionId: string; generation: number; expiresAt: number }>('fixture:active-submission');
      if (active) ctx.waitUntil(this.reconcileSubmission(active));
    });
  }

  override async alarm() {
    await this.ctx.storage.put('fixture:alarm-deliveries', (await this.ctx.storage.get<number>('fixture:alarm-deliveries') ?? 0) + 1);
    return super.alarm();
  }

  async configure(artifact: NativeArtifact, digest: string) {
    const bytes = new TextEncoder().encode(JSON.stringify(artifact));
    const actual = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), b => b.toString(16).padStart(2, '0')).join('');
    if (actual !== digest || bytes.length > 8 * 1024 * 1024 || Object.keys(artifact.modules).length > 128 ||
      artifact.className !== 'FlueDispatcherAgent' || artifact.versions.runtime !== '2.1.0' || artifact.versions.agents !== '0.20.1') {
      return { ok: false, reason: 'fixture-artifact-rejected' };
    }
    // Keep large generated bytes out of a single DO KV value. Eviction must
    // reload these exact bytes, never a moving file path or package reference.
    const chunkSize = 48 * 1024;
    for (let i = 0; i < bytes.length; i += chunkSize) await this.ctx.storage.put(`fixture:artifact:${i / chunkSize}`, bytes.slice(i, i + chunkSize));
    await this.ctx.storage.put({ 'fixture:artifact-chunks': Math.ceil(bytes.length / chunkSize), 'fixture:digest': digest });
    this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS fixture_parent_secret (secret TEXT)');
    this.ctx.storage.sql.exec("INSERT INTO fixture_parent_secret VALUES ('parent-only-sentinel')");
    return { ok: true, digest, sourceCommit: artifact.sourceCommit };
  }

  private async artifact(): Promise<NativeArtifact> {
    const count = await this.ctx.storage.get<number>('fixture:artifact-chunks');
    if (!count) throw new Error('Pinned native artifact not configured');
    const decoder = new TextDecoder();
    let json = '';
    for (let i = 0; i < count; i++) json += decoder.decode(await this.ctx.storage.get<Uint8Array>(`fixture:artifact:${i}`), { stream: true });
    return JSON.parse(json + decoder.decode());
  }

  private child(): Promise<Facet> {
    return this.facet ??= (async () => {
      const artifact = await this.artifact();
      const digest = await this.ctx.storage.get<string>('fixture:digest');
      // Rehydrate the exact persisted facet generation for read-only state
      // observation even after that generation reached `waiting`. The bound
      // transport still checks live `running` authority before every effect.
      const binding = await this.activityBinding();
      if (!binding || binding.deadline <= Date.now()) throw new Error('Native facet bridge identity is unavailable');
      // This root instance was reconstructed for this exact Activity generation.
      // A persisted facet may still hold the prior static RPC object; only this
      // fresh root can rebind it, so an old warm root cannot self-upgrade.
      this.reboundGeneration = binding.generation;
      const { exports } = this.ctx as unknown as { exports: {
        FixtureFlueTransport(options: { props: { activityId: string; generation: number } }): Fetcher;
      } };
      // A continuation generation receives a newly bound dynamic class while
      // retaining the same activity-private facet identity/SQLite. Reusing the
      // old Loader key would retain generation one's RPC props and make a valid
      // generation-two continuation indistinguishable from a stale warm caller.
      const worker = this.env.LOADER.get(`fixture:${this.name}:${digest}:${binding.generation}`, async () => ({
        compatibilityDate: artifact.compatibilityDate, compatibilityFlags: artifact.compatibilityFlags,
        mainModule: artifact.mainModule, modules: artifact.modules,
        // The facet receives only this direct, activity-private RPC target.
        // Its generation is captured here from the owner, never from delivery.
        env: { OPERATOR: exports.FixtureFlueTransport({ props: { activityId: this.name, generation: binding.generation } }) },
        globalOutbound: null,
      }));
      const { facets } = this.ctx as unknown as { facets: { get(name: string, init: () => unknown): Facet } };
      const child = facets.get('dispatcher', () => ({
        class: worker.getDurableObjectClass(artifact.className), id: this.env.FLUE_ROOT.idFromName('dispatcher'),
      }));
      // Pinned SDK bootstrap; the generated profile child supplies the exact
      // private root override before this handshake.
      await child._cf_initAsFacet('dispatcher', [{ className: 'FixtureFlueRoot', name: this.name }], 'dispatcher');
      return child;
    })();
  }

  private activityBinding() {
    return this.env.ACTIVITY.getByName(this.name).facetBridgeBinding();
  }

  /** The owner is the sole source for the generation captured by a new facet. */
  async facetBridgeBinding(generation?: number): Promise<FacetBridgeBinding> {
    const current = await this.activityBinding();
    if (!current || current.deadline <= Date.now() || current.status !== 'running') {
      return { generation: current?.generation ?? 0, status: 'denied' };
    }
    return { generation: current.generation, status: generation === undefined || generation === current.generation
      || this.reboundGeneration === current.generation ? 'current' : 'stale' };
  }

  async send(delivery: NativeDelivery) {
    try {
      const response = await (await this.child()).fetch(new Request('https://flue.internal/dispatcher', {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ kind: 'user', body: JSON.stringify(delivery) }),
      }));
      const body = await response.json() as { submissionId?: string };
      if (response.status === 202 && typeof body.submissionId === 'string') {
        const binding = await this.facetBridgeBinding();
        if (binding.status === 'current') {
          const active = { submissionId: body.submissionId, generation: binding.generation, expiresAt: Date.now() + 25_000 };
          await this.ctx.storage.put('fixture:active-submission', active);
          this.ctx.waitUntil(this.reconcileSubmission(active));
        }
      }
      return { status: response.status, body };
    } catch (error) {
      return { status: 501, body: { stage: 'native-facet-admission', error: String(error) } };
    }
  }

  private async reconcileSubmission(active: { submissionId: string; generation: number; expiresAt: number }): Promise<void> {
    while (Date.now() < active.expiresAt) {
      const current = await this.ctx.storage.get<typeof active>('fixture:active-submission');
      if (!current || current.submissionId !== active.submissionId || current.generation !== active.generation) return;
      const response = await (await this.child()).fetch(new Request('https://flue.internal/dispatcher'));
      const conversation = await response.json() as { settlements?: Array<{ submissionId?: string; outcome?: string }> };
      const settlement = conversation.settlements?.find(item => item.submissionId === active.submissionId);
      if (settlement) {
        const activity = this.env.ACTIVITY.getByName(this.name);
        if (settlement.outcome === 'completed') {
          await activity.commitDrive(active.generation, { schemaVersion: 1, status: 'waiting',
            checkpoint: { submissionId: active.submissionId } });
        } else {
          await activity.interruptDrive(active.generation);
        }
        await this.ctx.storage.delete('fixture:active-submission');
        return;
      }
      await new Promise(resolve => setTimeout(resolve, 50));
    }
    await this.env.ACTIVITY.getByName(this.name).interruptDrive(active.generation);
    await this.ctx.storage.delete('fixture:active-submission');
  }

  async snapshot() {
    let conversation: unknown = null;
    let facet: unknown = null;
    let failure: string | undefined;
    try {
      const child = await this.child();
      const response = await child.fetch(new Request('https://flue.internal/dispatcher'));
      conversation = await response.json();
      facet = await child.fixtureSnapshot();
    } catch (error) { failure = String(error); }
    return {
      instance: this.instance, conversation, facet, failure,
      alarmDeliveries: await this.ctx.storage.get<number>('fixture:alarm-deliveries') ?? 0,
      barrierReached: await this.ctx.storage.get<boolean>('fixture:barrier-reached') ?? false,
      external: await this.ctx.storage.get<ExternalReceipt[]>('fixture:external') ?? [],
      activity: await this.env.ACTIVITY.getByName(this.name).getBrowserDetail(),
      digest: await this.ctx.storage.get('fixture:digest'),
    };
  }

  async release() {
    await this.ctx.storage.put('fixture:released', true);
    this.releaseBarrier?.();
    return { released: true };
  }
  evict() { this.ctx.abort('Native Flue fixture root and facet eviction'); }
  async abort() {
    const response = await (await this.child()).fetch(new Request('https://flue.internal/dispatcher/abort', { method: 'POST' }));
    return { status: response.status, body: await response.json() };
  }

  /** Synthetic upstream, deliberately NOT the missing parent authority bridge. */
  async transport(request: Request): Promise<Response> {
    const path = new URL(request.url).pathname;
    if (path === '/fixture/inference') {
      // Official Workers-AI adapter consumes OpenAI-compatible SSE. Exactly one
      // real Flue tool is offered by the deterministic model, no model billing.
      const body = await request.json() as { input: { messages?: Array<{ role: string }> } };
      const done = body.input.messages?.at(-1)?.role === 'tool';
      const chunks = done ? [{ choices: [{ index: 0, delta: { content: 'Assessment complete' }, finish_reason: 'stop' }] }] : [
        { choices: [{ index: 0, delta: { tool_calls: [{ index: 0, id: 'fixture-tool', type: 'function',
          function: { name: 'assess_renovate', arguments: '{}' } }] }, finish_reason: null }] },
        { choices: [{ index: 0, delta: {}, finish_reason: 'tool_calls' }] },
      ];
      return new Response(chunks.map(chunk => `data: ${JSON.stringify(chunk)}\n\n`).join('') + 'data: [DONE]\n\n', {
        headers: { 'content-type': 'text/event-stream' },
      });
    }
    const delivery = await request.json() as NativeDelivery;
    if (path === '/fixture/barrier') {
      await this.ctx.storage.put('fixture:barrier-reached', true);
      if (!await this.ctx.storage.get('fixture:released')) await new Promise<void>(resolve => { this.releaseBarrier = resolve; });
      return Response.json({ released: true });
    }
    const external = await this.ctx.storage.get<ExternalReceipt[]>('fixture:external') ?? [];
    const receipt = { ...delivery, path, sequence: external.length + 1 };
    external.push(receipt);
    await this.ctx.storage.put('fixture:external', external);
    if (delivery.mode === 'unknown') {
      await this.ctx.storage.put('fixture:barrier-reached', true);
      // Accepted externally, response deliberately lost. Recovery must not
      // replay this ledger entry just because ToolStep did not record it.
      await new Promise<void>(resolve => { this.releaseBarrier = resolve; });
      throw new Error('Fixture lost external response');
    }
    return Response.json({ accepted: true, receipt, evidence: { repositoryId: 123, botId: 29139614, head: 'a'.repeat(40), checks: ['success'] } });
  }

  #path(path: FacetPath): void {
    if (!Array.isArray(path) || path.length < 2) throw new Error('Invalid facet bridge path');
    for (const segment of path) {
      if (!segment || typeof segment !== 'object' || Array.isArray(segment)
        || Object.keys(segment).length !== 2 || typeof segment.className !== 'string'
        || !segment.className || typeof segment.name !== 'string' || !segment.name || segment.name.includes('\0')) {
        throw new Error('Invalid facet bridge path');
      }
    }
    const [root, child] = path;
    if (root.className !== 'FixtureFlueRoot' || root.name !== this.name
      || child.className !== 'FlueDispatcherAgent' || child.name !== 'dispatcher') {
      throw new Error('Unauthorized facet bridge path');
    }
  }

  #agentsRoot(): AgentsFacetRootBridge {
    return Agent.prototype as unknown as AgentsFacetRootBridge;
  }

  override _cf_scheduleForFacet<T = string>(
    ownerPath: FacetPath, when: Date | string | number, callback: string, payload?: T,
    options?: { retry?: RetryOptions; idempotent?: boolean },
  ): Promise<{ schedule: Schedule<T>; created: boolean }> {
    this.#path(ownerPath);
    return (this.#agentsRoot()._cf_scheduleForFacet<T>).call(this, ownerPath, when, callback, payload, options);
  }
  override _cf_scheduleEveryForFacet<T = string>(
    ownerPath: FacetPath, intervalSeconds: number, callback: string, payload?: T,
    options?: { retry?: RetryOptions; _idempotent?: boolean },
  ): Promise<{ schedule: Schedule<T>; created: boolean }> {
    this.#path(ownerPath);
    return (this.#agentsRoot()._cf_scheduleEveryForFacet<T>).call(this, ownerPath, intervalSeconds, callback, payload, options);
  }
  override _cf_getScheduleForFacet(ownerPath: FacetPath, id: string): Promise<Schedule<unknown> | undefined> {
    this.#path(ownerPath);
    return this.#agentsRoot()._cf_getScheduleForFacet.call(this, ownerPath, id);
  }
  override _cf_listSchedulesForFacet(ownerPath: FacetPath, criteria?: ScheduleCriteria): Promise<Schedule<unknown>[]> {
    this.#path(ownerPath);
    return this.#agentsRoot()._cf_listSchedulesForFacet.call(this, ownerPath, criteria);
  }
  override _cf_cancelScheduleForFacet(ownerPath: FacetPath, id: string): Promise<{ ok: boolean; callback?: string }> {
    this.#path(ownerPath);
    return this.#agentsRoot()._cf_cancelScheduleForFacet.call(this, ownerPath, id);
  }
  override _cf_acquireFacetKeepAlive(ownerPath: FacetPath): Promise<string> {
    this.#path(ownerPath);
    return this.#agentsRoot()._cf_acquireFacetKeepAlive.call(this, ownerPath);
  }
  override _cf_releaseFacetKeepAlive(token: string): Promise<void> {
    return this.#agentsRoot()._cf_releaseFacetKeepAlive.call(this, token);
  }
  override _cf_registerFacetRun(ownerPath: FacetPath, runId: string): Promise<void> {
    this.#path(ownerPath);
    return this.#agentsRoot()._cf_registerFacetRun.call(this, ownerPath, runId);
  }
  override _cf_unregisterFacetRun(ownerPath: FacetPath, runId: string): Promise<void> {
    this.#path(ownerPath);
    return this.#agentsRoot()._cf_unregisterFacetRun.call(this, ownerPath, runId);
  }

  // The generated class is loaded dynamically, so it cannot appear in this
  // Worker's static ctx.exports registry. Route only the two root-alarm RPCs
  // that Agents uses to wake and recover this exact activity-private facet.
  override async _cf_dispatchScheduledCallback(ownerPath: FacetPath, row: unknown): Promise<boolean> {
    this.#path(ownerPath);
    return (await this.child())._cf_dispatchScheduledCallback(ownerPath, row);
  }
  override async _cf_checkRunFibersForFacet(ownerPath: FacetPath): Promise<number> {
    this.#path(ownerPath);
    return (await this.child())._cf_checkRunFibersForFacet(ownerPath);
  }
}

export class FixtureFlueTransport extends WorkerEntrypoint<NativeEnv> {
  #root(): Promise<FixtureFlueRootStub> {
    const { activityId } = this.ctx.props as { activityId: string; generation: number };
    return getAgentByName(this.env.FLUE_ROOT, activityId);
  }

  async #current(): Promise<FacetBridgeBinding> {
    const { generation } = this.ctx.props as { activityId: string; generation: number };
    return (await this.#root()).facetBridgeBinding(generation);
  }

  async #bridge<T>(call: (root: FixtureFlueRootStub) => Promise<T>): Promise<T> {
    const binding = await this.#current();
    if (binding.status !== 'current') throw new Error(`Facet bridge generation ${binding.status}`);
    return call(await this.#root());
  }

  async fetch(request: Request) {
    const binding = await this.#current();
    if (binding.status !== 'current') {
      return Response.json({ error: 'Facet bridge generation rejected' }, { status: binding.status === 'stale' ? 409 : 403 });
    }
    return (await this.#root()).transport(request);
  }

  async _cf_scheduleForFacet<T = string>(
    ownerPath: FacetPath, when: Date | string | number, callback: string, payload?: T,
    options?: { retry?: RetryOptions; idempotent?: boolean },
  ): Promise<{ schedule: Schedule<T>; created: boolean }> {
    return this.#bridge(root => root._cf_scheduleForFacet(ownerPath, when, callback, payload, options));
  }
  async _cf_scheduleEveryForFacet<T = string>(
    ownerPath: FacetPath, intervalSeconds: number, callback: string, payload?: T,
    options?: { retry?: RetryOptions; _idempotent?: boolean },
  ): Promise<{ schedule: Schedule<T>; created: boolean }> {
    return this.#bridge(root => root._cf_scheduleEveryForFacet(ownerPath, intervalSeconds, callback, payload, options));
  }
  async _cf_getScheduleForFacet(ownerPath: FacetPath, id: string): Promise<Schedule<unknown> | undefined> {
    return this.#bridge(root => root._cf_getScheduleForFacet(ownerPath, id));
  }
  async _cf_listSchedulesForFacet(ownerPath: FacetPath, criteria?: ScheduleCriteria): Promise<Schedule<unknown>[]> {
    return this.#bridge(root => root._cf_listSchedulesForFacet(ownerPath, criteria));
  }
  async _cf_cancelScheduleForFacet(ownerPath: FacetPath, id: string): Promise<{ ok: boolean; callback?: string }> {
    return this.#bridge(root => root._cf_cancelScheduleForFacet(ownerPath, id));
  }
  async _cf_acquireFacetKeepAlive(ownerPath: FacetPath): Promise<string> {
    return this.#bridge(root => root._cf_acquireFacetKeepAlive(ownerPath));
  }
  async _cf_releaseFacetKeepAlive(token: string): Promise<void> {
    return this.#bridge(root => root._cf_releaseFacetKeepAlive(token));
  }
  async _cf_registerFacetRun(ownerPath: FacetPath, runId: string): Promise<void> {
    return this.#bridge(root => root._cf_registerFacetRun(ownerPath, runId));
  }
  async _cf_unregisterFacetRun(ownerPath: FacetPath, runId: string): Promise<void> {
    return this.#bridge(root => root._cf_unregisterFacetRun(ownerPath, runId));
  }
}

export async function flueFixture(request: Request, env: NativeEnv) {
  const id = new URL(request.url).searchParams.get('activity')!;
  const root = await getAgentByName(env.FLUE_ROOT, id);
  const command = await request.json<FlueFixtureCommand>();
  switch (command.action) {
    case 'configure': return Response.json(await root.configure(command.artifact, command.digest));
    case 'send': return Response.json(await root.send(command.delivery));
    case 'snapshot': return Response.json(await root.snapshot());
    case 'release': return Response.json(await root.release());
    case 'abort': return Response.json(await root.abort());
    case 'evict':
      await root.evict().catch(() => {});
      return Response.json({ evicted: true });
  }
}
